#!/usr/bin/env python3
"""
ODE Micro-Practice Quiz Generator
Author: Antigravity AI Pair Programmer
Description: Automatically extracts YouTube transcripts, queries the Gemini API
             to generate a conceptually clear 5-question micro-practice quiz in LaTeX,
             adds the quiz to a local persistent database cache, and compiles the 
             updated quiz directly into the Ordinary Differential Equations Study Roadmap dashboard.
"""

import os
import sys
import json
import argparse
import subprocess
import shutil

# Title Banner
BANNER = r"""
========================================================================
   __  __ ___ ____ ____   ___     ___  _   _ ___ _____ 
  |  \/  |_ _/ ___|  _ \ / _ \   / _ \| | | |_ _|__  / 
  | |\/| || | |   | |_) | | | | | | | | | | || |  / /  
  | |  | || | |___|  _ <| |_| | | |_| | |_| || | / /_  
  |_|  |_|___\____|_| \_\\___/   \__\_\\___/|___/____| 
                 Q U I Z   G E N E R A T O R
========================================================================
"""

def check_dependencies():
    """Checks and verifies that necessary dependencies are installed in the environment."""
    missing = []
    
    try:
        import youtube_transcript_api
    except ImportError:
        missing.append("youtube-transcript-api")
        
    try:
        import google.generativeai
    except ImportError:
        missing.append("google-generativeai")
        
    if missing:
        print("\n" + "!" * 80)
        print("[!] Missing required python libraries for quiz generation!")
        print("Please install them by running:")
        print(f"    pip install {' '.join(missing)}")
        print("!" * 80 + "\n")
        sys.exit(1)

def get_gemini_api_key():
    """Retrieves the Gemini API key from the environment variables."""
    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        print("\n" + "!" * 80)
        print("[!] ERROR: 'GEMINI_API_KEY' environment variable not set!")
        print("\nPlease configure your Google Gemini API key by running:")
        print("\n  On Windows PowerShell:")
        print('    $env:GEMINI_API_KEY="your_api_key_here"')
        print("\n  On Windows Command Prompt (CMD):")
        print('    set GEMINI_API_KEY=your_api_key_here')
        print("\n  On Linux / macOS:")
        print('    export GEMINI_API_KEY="your_api_key_here"')
        print("\nYou can get a free Gemini API key from Google AI Studio:")
        print("https://aistudio.google.com/")
        print("!" * 80 + "\n")
        sys.exit(1)
    return key

def fetch_transcript(video_id):
    """Fetches the English transcript of the YouTube video using youtube-transcript-api."""
    from youtube_transcript_api import YouTubeTranscriptApi
    from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound
    
    print(f"[*] Downloading transcript for video ID '{video_id}'...")
    try:
        # Request English transcripts specifically, falling back to English autogenerated
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
        text = " ".join([item['text'] for item in transcript_list])
        print(f"[+] Downloaded transcript successfully! ({len(text)} characters)")
        return text
    except TranscriptsDisabled:
        sys.exit(f"[!] Error: Transcripts are disabled for video '{video_id}'. Cannot generate quiz.")
    except NoTranscriptFound:
        sys.exit(f"[!] Error: No English transcript or automatic caption found for video '{video_id}'.")
    except Exception as e:
        sys.exit(f"[!] Error downloading transcript: {e}")

def generate_quiz(video_id, video_title, chapter_number, transcript, api_key, model_name):
    """Calls the Gemini API to generate the LaTeX micro quiz JSON based on the transcript."""
    import google.generativeai as genai
    
    print(f"[*] Initializing Gemini API connection using '{model_name}'...")
    genai.configure(api_key=api_key)
    
    prompt = f"""
You are an expert university mathematics professor specializing in Ordinary Differential Equations (ODEs).
I have an educational lecture video titled "{video_title}" (ID: {video_id}) mapped to Chapter {chapter_number} of my course.
Here is the complete English transcript of the video:

---
{transcript}
---

Based ONLY on the provided lecture transcript details, generate a conceptually clear and academically rigorous 5-question multiple-choice micro-practice quiz to test students' comprehension of the core definitions and techniques discussed.

Follow these strict pedagogical rules:
1. Questions must test distinct key concepts, models, or formulas covered in this specific lecture.
2. Each question must have exactly 4 answer options (choices).
3. Only ONE option can be marked as correct (`isCorrect: true`). The other three must be false (`isCorrect: false`).
4. Each option MUST have a clear, academic rationale explaining why it is correct or incorrect based on the lecture contents.
5. Provide a helpful hint for students who get stuck.
6. Use KaTeX/LaTeX formatting for all mathematical symbols, expressions, and equations:
   - Enclose inline math in single dollar signs, like $y(x) = C e^{{kt}}$ or $\\frac{{dy}}{{dx}}$.
   - Enclose block equations in double dollar signs, like $$\\frac{{d^2y}}{{dx^2}} + y = 0$$.
   - Ensure all derivatives, variables, limits, trigonometric functions, and integrals are styled in standard LaTeX.
7. Return a clean, descriptive title for the quiz (e.g., "Micro-Practice: Separation of Variables").

Your output must be strict, valid JSON in the exact format shown below, with the outer key being "inline_{video_id}_definitions":

{{
  "inline_{video_id}_definitions": {{
    "quiz_id": "inline_{video_id}_definitions",
    "chapter_number": {chapter_number},
    "video_id": "{video_id}",
    "title": "Micro-Practice: [Insert Core Lesson Topic]",
    "questions": [
      {{
        "questionNumber": 1,
        "question": "[LaTeX Question Text]",
        "answerOptions": [
          {{
            "text": "[LaTeX Option A]",
            "rationale": "[LaTeX rationale explaining why correct/incorrect]",
            "isCorrect": false
          }},
          {{
            "text": "[LaTeX Option B]",
            "rationale": "[LaTeX rationale explaining why correct/incorrect]",
            "isCorrect": true
          }},
          {{
            "text": "[LaTeX Option C]",
            "rationale": "[LaTeX rationale explaining why correct/incorrect]",
            "isCorrect": false
          }},
          {{
            "text": "[LaTeX Option D]",
            "rationale": "[LaTeX rationale explaining why correct/incorrect]",
            "isCorrect": false
          }}
        ],
        "hint": "[LaTeX Hint Text]"
      }}
    ]
  }}
}}

Ensure the output is raw JSON only. Do not wrap it in markdown code fences (like ```json ... ```) or include any chat introduction or summary.
"""

    try:
        model = genai.GenerativeModel(model_name)
        # Attempt to enforce JSON schema output if supported
        response = model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"}
        )
        
        raw_text = response.text.strip()
        
        # Clean markdown code fences if Gemini ignores request
        if raw_text.startswith("```json"):
            raw_text = raw_text[7:]
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]
        raw_text = raw_text.strip()
        
        quiz_data = json.loads(raw_text)
        print("[+] Successfully received and parsed valid quiz JSON from Gemini!")
        return quiz_data
    except json.JSONDecodeError as jde:
        print(f"[!] Error: Gemini did not return valid JSON. Raw response:\n{response.text}")
        sys.exit(f"[!] JSON parsing failed: {jde}")
    except Exception as e:
        sys.exit(f"[!] Gemini API Error: {e}")

def save_and_compile(quiz_obj):
    """Saves the generated quiz to quizzes_cache.json and triggers ode_sorter recompilation."""
    cache_file = "quizzes_cache.json"
    cache = {}
    
    # 1. Load existing dynamic quizzes if they exist
    if os.path.exists(cache_file):
        try:
            with open(cache_file, "r", encoding="utf-8") as f:
                cache = json.load(f)
            print(f"[*] Loaded {len(cache)} existing dynamic quizzes from '{cache_file}'")
        except Exception as e:
            print(f"[*] Warning: Could not parse existing '{cache_file}': {e}. Starting fresh.")
            
    # 2. Merge new quiz (overwriting if key already exists)
    cache.update(quiz_obj)
    
    # 3. Save cache
    try:
        with open(cache_file, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
        print(f"[+] Saved updated dynamic database to '{cache_file}'")
    except Exception as e:
        sys.exit(f"[!] Error saving to '{cache_file}': {e}")
        
    # 4. Trigger ode_sorter recompilation
    print("\n[*] Rebuilding study guide pages...")
    if os.path.exists("ode_sorter.py"):
        try:
            # Run the Python compiler script
            result = subprocess.run([sys.executable, "ode_sorter.py"], capture_output=True, text=True, check=True)
            print(result.stdout)
            
            # Copy recompiled files to deployment locations
            if os.path.exists("sorted_playlist.html"):
                shutil.copyfile("sorted_playlist.html", "Ordinary Differential Equations Study Roadmap.html")
                shutil.copyfile("sorted_playlist.html", "index.html")
                print("[+] Dashboard compilation successful!")
                print("    - Ordinary Differential Equations Study Roadmap.html (UPDATED)")
                print("    - index.html (UPDATED)")
            else:
                print("[!] Error: 'sorted_playlist.html' was not found after compilation.")
        except subprocess.CalledProcessError as cpe:
            print(f"[!] Compilation failed: {cpe.stderr}")
            sys.exit(1)
    else:
        sys.exit("[!] Error: 'ode_sorter.py' compiler script not found in active directory.")

def main():
    print(BANNER)
    check_dependencies()
    api_key = get_gemini_api_key()
    
    parser = argparse.ArgumentParser(description="Automate LaTeX Micro-Practice quiz generation from video transcripts.")
    parser.add_argument("--video-id", type=str, help="YouTube Video ID to generate the micro quiz for.")
    parser.add_argument("--model", type=str, default="gemini-2.5-flash", help="Gemini API Model name.")
    args = parser.parse_args()
    
    # 1. Check if video ID is specified. If not, load from cache and present choice.
    target_id = args.video_id
    video_title = "Unknown Lecture Video"
    chapter_number = 1
    
    # Attempt to load catalog from cache to verify / map metadata
    playlist_cache = "playlist_cache.json"
    catalog = []
    if os.path.exists(playlist_cache):
        try:
            with open(playlist_cache, "r", encoding="utf-8") as f:
                catalog = json.load(f)
        except Exception as e:
            print(f"[*] Warning: Could not read '{playlist_cache}': {e}")
            
    # Try importing ode_sorter to get exact syllabus metadata
    syllabus = []
    if os.path.exists("ode_sorter.py"):
        try:
            sys.path.append(os.getcwd())
            import ode_sorter
            videos = ode_sorter.get_videos()
            syllabus = ode_sorter.apply_fallback_sorting(videos)
        except Exception as e:
            print(f"[*] Warning: Could not load syllabus metadata from ode_sorter: {e}")
            
    if not target_id:
        if catalog:
            print("[*] No Video ID provided. Here are the first 10 videos in your catalog:")
            for idx, item in enumerate(catalog[:10]):
                print(f"  {idx + 1}. [ {item['id']} ] - {item['title']}")
            print("\nPlease rerun the script with --video-id <ID>.")
            print("Example: python generate_micro_quizzes.py --video-id 7Y-frhf-1Zk")
            sys.exit(0)
        else:
            sys.exit("[!] Error: No Video ID provided and 'playlist_cache.json' was not found.")
            
    # 2. Look up video metadata
    metadata_found = False
    if syllabus:
        for ch_idx, chapter in enumerate(syllabus):
            for v in chapter.get("videos", []):
                if v["id"] == target_id:
                    video_title = v["title"]
                    chapter_number = ch_idx + 1
                    metadata_found = True
                    break
            if metadata_found:
                break
                
    if not metadata_found and catalog:
        for item in catalog:
            if item["id"] == target_id:
                video_title = item["title"]
                metadata_found = True
                break
                
    print(f"\nTarget Video:")
    print(f"  - Video ID:   {target_id}")
    print(f"  - Title:      {video_title}")
    print(f"  - Chapter:    {chapter_number}")
    print("-" * 50 + "\n")
    
    # 3. Fetch Transcript
    transcript = fetch_transcript(target_id)
    
    # 4. Generate Quiz via Gemini
    quiz_obj = generate_quiz(target_id, video_title, chapter_number, transcript, api_key, args.model)
    
    # 5. Save and Recompile
    save_and_compile(quiz_obj)
    
    print("\n========================================================================")
    print(f"[+] MICRO-PRACTICE GENERATION PIPELINE COMPLETE!")
    print(f"[-] Quiz ID: inline_{target_id}_definitions")
    print(f"[-] Video ID: {target_id}")
    print(f"[-] Location: Injected inline directly beneath Video card inside the grid.")
    print("[-] Open 'Ordinary Differential Equations Study Roadmap.html' to review!")
    print("========================================================================\n")

if __name__ == "__main__":
    main()
