/* Unit 7 checkpoint widgets.

   7.1 exactness_test_checker
   7.2 module override for partial_derivative_checker (exactness intuition)
   7.3 desmos_potential_surface_visualizer
   7.4 special_integrating_factor_calculator
   7.5 almost_exact_transformer
   7.6 module override for conservative_field_tester (the bridge to fields)
   7.7 thermodynamic_state_function_sorter */

(function () {

    // ---------- 7.1 The full exactness workflow ----------

    CheckpointRegistry.register("exactness_test_checker", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "Take the equation (3x^2 + 2y) dx + (2x + 4y) dy = 0 from suspicion to solution: run the exactness test, then reconstruct the function F whose level curves solve the equation. Any valid F is accepted.",
            guidingQuestions: [
                "Here M = 3x^2 + 2y and N = 2x + 4y. The test compares the y derivative of M against the x derivative of N.",
                "Once the test passes, integrate M with respect to x, allowing the integration constant to be a function of y. Then differentiate with respect to y and match against N to pin that function down."
            ]
        }, function (body, api) {
            CheckpointCore.buildExpressionTask(body, api, {
                prompt: "Test and solve (3x^2 + 2y) dx + (2x + 4y) dy = 0.",
                buttonLabel: "Check My Work",
                fields: [
                    {
                        label: "Partial of M with respect to y:",
                        placeholder: "a number or expression",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "2", ["x", "y"], { min: 0.4, max: 2.2 });
                        }
                    },
                    {
                        label: "Partial of N with respect to x:",
                        placeholder: "a number or expression",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "2", ["x", "y"], { min: 0.4, max: 2.2 });
                        }
                    },
                    {
                        label: "Verdict:",
                        options: [
                            "Exact, the cross partials agree",
                            "Not exact, the cross partials differ",
                            "The test does not apply here"
                        ],
                        check: function (value) {
                            return { ok: value === "Exact, the cross partials agree" };
                        }
                    },
                    {
                        label: "F(x, y) whose level curves F = C solve the equation:",
                        placeholder: "for example x^3 + ...",
                        check: function (value) {
                            return CheckpointCore.gradientMatches(value, ["3*x^2+2*y", "2*x+4*y"], ["x", "y"]);
                        }
                    }
                ]
            });
        });
    });

    // ---------- 7.2 Module override: where exact equations come from ----------

    CheckpointRegistry.registerForModule("7.2 Exact Equations Intuition", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "Exact equations are total differentials in disguise. Start from the function F(x, y) = x^2 y^3 and build the exact equation it generates: along any level curve of F, the total differential dF must vanish.",
            guidingQuestions: [
                "The total differential is dF = F_x dx + F_y dy. Differentiate x^2 y^3 each way, holding the other variable frozen.",
                "Setting dF = 0 says F does not change. Geometrically, on which family of curves is a function guaranteed not to change?"
            ]
        }, function (body, api) {
            CheckpointCore.buildExpressionTask(body, api, {
                prompt: "Build the exact equation M dx + N dy = 0 generated by F = x^2 y^3.",
                buttonLabel: "Check My Construction",
                fields: [
                    {
                        label: "M = partial of F with respect to x:",
                        placeholder: "in x and y",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "2*x*y^3", ["x", "y"], { min: 0.4, max: 2.0 });
                        }
                    },
                    {
                        label: "N = partial of F with respect to y:",
                        placeholder: "in x and y",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "3*x^2*y^2", ["x", "y"], { min: 0.4, max: 2.0 });
                        }
                    },
                    {
                        label: "The solutions of M dx + N dy = 0 are:",
                        options: [
                            "The level curves F(x, y) = C",
                            "The graphs y = F(x, C)",
                            "Straight lines through the origin",
                            "The zeros of F"
                        ],
                        check: function (value) {
                            return { ok: value === "The level curves F(x, y) = C" };
                        }
                    }
                ]
            });
        });
    });

    // ---------- 7.3 Solutions as level sets of a potential surface ----------

    CheckpointRegistry.register("desmos_potential_surface_visualizer", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "The exact equation 2x dx - 2y dy = 0 has the potential phi(x, y) = x^2 - y^2, a saddle surface. Its level curves, shown for your chosen c, are the solution curves of the equation. Slide c until the level curve passes through the marked point.",
            guidingQuestions: [
                "The marked point lies on the level curve whose constant equals phi evaluated there. Substitute (2, 1) into x^2 - y^2.",
                "Each value of c selects one horizontal slice of the saddle. Slide until the slice owns the point."
            ]
        }, function (body, api) {
            const calc = CheckpointCore.desmosGraph(body, {});
            if (!calc) return;

            calc.setMathBounds({ left: -5, right: 5, bottom: -3.5, top: 3.5 });
            calc.setExpressions([
                { id: "sliderC", latex: "c=0", sliderBounds: { min: -6, max: 6, step: 0.1 } },
                { id: "level", latex: "x^{2}-y^{2}=c", color: "#6042a6" },
                { id: "mark", latex: "(2, 1)", color: "#c74440", label: "Target", showLabel: true, dragMode: "NONE" }
            ]);

            const cValue = CheckpointCore.observeValue(calc, "c");

            body.appendChild(CheckpointCore.checkButton("Check My Level Curve", function () {
                if (!isFinite(cValue.value)) {
                    api.error("Move the c slider first, then check.");
                    return;
                }
                if (Math.abs(cValue.value - 3) <= 0.15) {
                    api.pass("Correct. Solving an exact equation never finds y explicitly: it finds the surface whose contour lines are the solutions.");
                } else {
                    api.fail();
                }
            }));
        });
    });

    // ---------- 7.4 Repair a non-exact equation ----------

    CheckpointRegistry.register("special_integrating_factor_calculator", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "The equation (3xy + y^2) dx + (x^2 + xy) dy = 0 fails the exactness test, but it can be repaired. Compute the diagnostic ratio, recognize that it depends on x alone, and produce the integrating factor. Any constant multiple is accepted.",
            guidingQuestions: [
                "Compute the y derivative of M and the x derivative of N, subtract, and divide by N. Factor the numerator and denominator before despairing: a dramatic cancellation is waiting.",
                "When the ratio depends on x alone, the integrating factor obeys mu' = ratio times mu. Your ratio is 1/x. Which simple power of x has a derivative equal to itself divided by x?"
            ]
        }, function (body, api) {
            CheckpointCore.buildExpressionTask(body, api, {
                prompt: "Repair (3xy + y^2) dx + (x^2 + xy) dy = 0.",
                buttonLabel: "Check My Repair",
                fields: [
                    {
                        label: "The ratio (M_y - N_x) / N, simplified:",
                        placeholder: "in x and y, it will simplify",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "1/x", ["x", "y"], { min: 0.5, max: 2.4 });
                        }
                    },
                    {
                        label: "Integrating factor mu(x) =",
                        placeholder: "an expression in x",
                        check: function (value) {
                            const offending = CheckpointCore.usesOnlyVariables(value, ["x"]);
                            if (offending) {
                                return { ok: false, error: "This integrating factor depends on x only. The symbol " + offending + " is not expected." };
                            }
                            return CheckpointCore.satisfiesGrowthLaw(value, "1/x", "x", { min: 0.5, max: 2.4 });
                        }
                    },
                    {
                        label: "After multiplying the equation by mu, it becomes:",
                        options: [
                            "Exact, and solvable by the potential method",
                            "Separable",
                            "Linear in y",
                            "Unchanged, integrating factors only help linear equations"
                        ],
                        check: function (value) {
                            return { ok: value === "Exact, and solvable by the potential method" };
                        }
                    }
                ]
            });
        });
    });

    // ---------- 7.5 Almost exact, fully worked ----------

    CheckpointRegistry.register("almost_exact_transformer", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "The equation y dx - x dy = 0 is famously not exact, yet multiplying by mu = 1/y^2 transforms it completely. Carry out the transformation, verify exactness, and recover the potential. Any valid potential is accepted.",
            guidingQuestions: [
                "Multiply each piece by 1/y^2: what do M = y and N = -x become?",
                "Retest the transformed pieces: differentiate the new M with respect to y and the new N with respect to x. They now agree, so integrate the new M with respect to x to begin recovering F."
            ]
        }, function (body, api) {
            CheckpointCore.buildExpressionTask(body, api, {
                prompt: "Transform y dx - x dy = 0 with mu = 1/y^2.",
                buttonLabel: "Check My Transformation",
                fields: [
                    {
                        label: "New M = y times mu:",
                        placeholder: "in y",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "1/y", ["x", "y"], { min: 0.5, max: 2.2 });
                        }
                    },
                    {
                        label: "New N = -x times mu:",
                        placeholder: "in x and y",
                        check: function (value) {
                            return CheckpointCore.expressionsMatch(value, "-x/y^2", ["x", "y"], { min: 0.5, max: 2.2 });
                        }
                    },
                    {
                        label: "A potential F for the transformed equation:",
                        placeholder: "its gradient must be (new M, new N)",
                        check: function (value) {
                            return CheckpointCore.gradientMatches(value, ["1/y", "-x/y^2"], ["x", "y"], { min: 0.5, max: 2.2 });
                        }
                    }
                ]
            });
        });
    });

    // ---------- 7.6 Module override: the bridge between two worlds ----------

    CheckpointRegistry.registerForModule("7.6 Exact Equations and Conservative Vector Fields", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "Exact equations and conservative vector fields are the same mathematics wearing different clothes. Three questions test whether you can translate between the two languages.",
            guidingQuestions: []
        }, function (body, api) {
            CheckpointCore.buildLogicGate(body, api, {
                questions: [
                    {
                        text: "The exact equation M dx + N dy = 0 corresponds to which statement about the vector field F = (M, N)?",
                        guide: "Exactness delivered a function F whose partial derivatives are M and N. In the language of vector calculus, what is a field that arises as the gradient of a function called?",
                        options: [
                            { text: "F is conservative, it is the gradient of a potential", correct: true },
                            { text: "F is tangent to every solution curve", correct: false },
                            { text: "F has constant magnitude", correct: false },
                            { text: "F points away from the origin", correct: false }
                        ]
                    },
                    {
                        text: "Solving an exact equation amounts to finding:",
                        guide: "The method integrates M and N back into a single function, and the answer arrives as a family of implicit curves. Which object plays both roles at once?",
                        options: [
                            { text: "A potential function whose level curves are the solutions", correct: true },
                            { text: "An explicit formula y = f(x)", correct: false },
                            { text: "The arc length of the field lines", correct: false },
                            { text: "A particular solution with no constant", correct: false }
                        ]
                    },
                    {
                        text: "The exactness test and the conservative field test are the same comparison of cross partials. What single theorem makes both work?",
                        guide: "Both tests succeed because the candidate M and N are meant to be the two first partials of one function, and second partials of that function must commute. Whose theorem says mixed partials agree?",
                        options: [
                            { text: "Clairaut's theorem on equality of mixed partials", correct: true },
                            { text: "The fundamental theorem of calculus", correct: false },
                            { text: "The existence and uniqueness theorem", correct: false },
                            { text: "The mean value theorem", correct: false }
                        ]
                    }
                ]
            });
        });
    });

    // ---------- 7.7 State functions and path dependence ----------

    CheckpointRegistry.register("thermodynamic_state_function_sorter", function (container, moduleData) {
        CheckpointCore.shell(container, moduleData, {
            description: "Thermodynamics is where exact differentials earn a living. A state function depends only on where the system is, so its differential is exact and integrals of it are path independent. Heat and work are different: they depend on the route taken. Sort each quantity.",
            guidingQuestions: [
                "Ask of each quantity: if a gas moves from state A to state B by two different processes, must this quantity change by the same amount either way?",
                "Internal energy depends only on the current state. But two processes between the same endpoints can transfer different amounts of heat and perform different amounts of work, only their difference is fixed."
            ]
        }, function (body, api) {
            CheckpointCore.buildCategorySorter(body, api, {
                prompt: "Classify each thermodynamic quantity.",
                categories: ["State function, exact differential", "Path dependent, inexact differential"],
                items: [
                    { text: "Internal energy U", category: "State function, exact differential" },
                    { text: "Heat q transferred during a process", category: "Path dependent, inexact differential" },
                    { text: "Work w performed during a process", category: "Path dependent, inexact differential" },
                    { text: "Entropy S", category: "State function, exact differential" },
                    { text: "Volume V", category: "State function, exact differential" },
                    { text: "Enthalpy H", category: "State function, exact differential" }
                ]
            });
        });
    });

})();
