#!/usr/bin/env python3
"""Render a Unit Reference Guide .tex from a mined curriculum JSON.

Reads ``unit13_data.json`` and writes
``app/assets/markdowns/Unit-13-Reference-Guide.tex``.

The renderer is the bridge stage of the JSON -> LaTeX -> PDF pipeline. It pulls
in the shared style harness via ``\\input{app/assets/markdowns/preamble.tex}`` so
the document inherits the exact palette, typography, and the six custom boxes
defined in LATEX_STYLE_GUIDE.md, then loops the JSON modules to emit the 6-box
matrix (topicsbox, formulabox, methodbox, examplebox, conceptbox, warningbox).

Conventions enforced here:
  * Every parameterized box uses a braced title ``title={#1}`` (supplied via the
    box's optional argument), matching the protected-title rule of the guide.
  * Every live step inside a worked example is wrapped in
    ``\\textcolor{workpurple}{...}`` so the running purple math reads identically
    to the examplebox frame color.

Run from the repository root so the relative ``\\input`` path resolves:
    python scripts/render_latex.py
"""

from __future__ import annotations

import json
import os

# Paths are resolved relative to the repository root (the script's parent dir).
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(REPO_ROOT, "unit13_data.json")
OUT_PATH = os.path.join(REPO_ROOT, "app", "assets", "markdowns", "Unit-13-Reference-Guide.tex")
PREAMBLE_INPUT = "app/assets/markdowns/preamble.tex"


def display(body: str) -> str:
    """A display-math block."""
    return f"\\[ {body} \\]"


def purple_display(body: str) -> str:
    """A display-math block with the whole line tracked in worked-example purple."""
    return f"\\[ \\textcolor{{workpurple}}{{{body}}} \\]"


def render_topicsbox(glance: dict) -> str:
    lines = [f"\\begin{{topicsbox}}[{glance['title']}]", glance["summary"], ""]
    lines.append("\\begin{itemize}[leftmargin=1.4em, itemsep=3pt]")
    for bullet in glance["bullets"]:
        lines.append(f"    \\item {bullet}")
    lines.append("\\end{itemize}")
    lines.append("\\end{topicsbox}")
    return "\n".join(lines)


def render_formulabox(formula: dict) -> str:
    return "\n".join([
        f"\\begin{{formulabox}}[{formula['title']}]",
        display(formula["body"]),
        "\\end{formulabox}",
    ])


def render_methodbox(method: dict) -> str:
    lines = [f"\\begin{{methodbox}}[{method['title']}]", "\\begin{enumerate}[leftmargin=1.6em]"]
    for step in method["steps"]:
        lines.append(f"    \\item {step}")
    lines.append("\\end{enumerate}")
    lines.append("\\end{methodbox}")
    return "\n".join(lines)


def render_examplebox(example: dict) -> str:
    lines = [f"\\begin{{examplebox}}[{example['title']}]"]
    if example.get("setup"):
        lines.append(example["setup"])
    # Each live solution step is tracked in workpurple per the style guide.
    for step in example["steps"]:
        lines.append(purple_display(step))
    lines.append("\\end{examplebox}")
    return "\n".join(lines)


def render_conceptbox(concept: dict) -> str:
    return "\n".join([
        f"\\begin{{conceptbox}}[{concept['title']}]",
        concept["body"],
        "\\end{conceptbox}",
    ])


def render_warningbox(warning: dict) -> str:
    return "\n".join([
        f"\\begin{{warningbox}}[{warning['title']}]",
        warning["body"],
        "\\end{warningbox}",
    ])


def render_module(module: dict) -> str:
    """Emit one numbered sub-module: heading, topics lead-in, then the box matrix."""
    parts = [
        f"% ---- Module {module['id']} {'-' * 50}",
        f"\\subsection{{{module['title']}}}",
        f"\\emph{{{module['topics']}}}",
        "",
    ]
    for formula in module["formulas"]:
        parts.append(render_formulabox(formula))
        parts.append("")
    parts.append(render_methodbox(module["methodology"]))
    parts.append("")
    for example in module["examples"]:
        parts.append(render_examplebox(example))
        parts.append("")
    parts.append(render_conceptbox(module["concept"]))
    parts.append("")
    parts.append(render_warningbox(module["warning"]))
    parts.append("\n\\vspace{0.8em}\n")
    return "\n".join(parts)


def render_document(data: dict) -> str:
    out = []
    out.append("% Unit 13 Reference Guide --- Series Solutions")
    out.append("% AUTO-GENERATED by scripts/render_latex.py from unit13_data.json.")
    out.append("% Do not edit by hand; edit the JSON and re-run the renderer.")
    out.append("% Shared style harness pulled from the unified preamble input.")
    out.append("")
    out.append(f"\\input{{{PREAMBLE_INPUT}}}")
    out.append("")
    out.append("\\begin{document}")
    out.append("")
    # Title block.
    out.append("\\begin{center}")
    out.append(f"    {{\\LARGE \\bfseries {data['title']}}}\\\\[6pt]")
    out.append("    {\\large Prepared by Staples Education}\\\\[4pt]")
    out.append(f"    {{\\itshape Unit {data['unitNumber']}: {data['subtitle']}}}")
    out.append("\\end{center}")
    out.append("")
    out.append("\\vspace{0.4em}")
    out.append("\\tableofcontents")
    out.append("\\vspace{0.4em}")
    out.append("")
    # Unit-level overview capsule.
    out.append(render_topicsbox(data["atAGlance"]))
    out.append("")
    out.append("\\vspace{0.6em}")
    out.append("")
    # Force the section counter to the unit number so sub-modules read 13.1, 13.2, ...
    out.append(f"\\setcounter{{section}}{{{data['unitNumber']}}}")
    out.append("")
    for module in data["modules"]:
        out.append(render_module(module))
    out.append("\\end{document}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    with open(DATA_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    tex = render_document(data)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(tex)
    n_boxes = sum(len(m["formulas"]) + 4 for m in data["modules"]) + 1
    print(f"Wrote {OUT_PATH}")
    print(f"  modules: {len(data['modules'])}, boxes emitted: {n_boxes}")


if __name__ == "__main__":
    main()
